# Generated by Django 5.2.5 on 2025-08-30 09:23

import airports_management_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports_management_system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airports_management_system.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airports_management_system.models.upload_image_path),
        ),
    ]
